### ISSUE TITLE
store.dispatch(FarceActions.push('/new/path')); doesn't re-render page

### ISSUE THREAD

**Issue by ilyhryh** [4Catalyzer/farce#123] opened 2019-05-11 08:04 UTC
I use found + farce + found-relay + redux.

```js
onClick={() => store.dispatch(FarceActions.push(`/${item._id}`))}
```

It changes URL and pushes new entry to store, but doesn't re-render page. I want the same behavior as `<Link />` component, but without using it. 

```html
<tr onClick={() => store.dispatch(FarceActions.push(`/${item._id}`))} >
  <td>something</td>
  <td>something</td>
  ...
  <td>something</td>
</tr>
```

**Comment by taion** [comment] 2019-05-11 20:48
dupe of https://github.com/4Catalyzer/found/issues/369

**Closed by taion** 2019-05-11 20:48 UTC
